[run]
deadline = "5m"

[linters]
disable-all = true
enable = [
  "deadcode",
  "goconst",
  "gocritic",
  "gofmt",
  "goimports",
  "gosimple",
  "ineffassign",
  "scopelint",
  "staticcheck",
  "stylecheck",
  "unconvert",
  "unused",
  "whitespace",
]

[linter-settings]
  [linter-settings.errcheck]
  check-blank = true
  check-type-assertions = true

[issues]
  max-same-issues = 50
  max-issues-per-linter = 50
  exclude = [
    # scopelint chokes on filepath.Walk
    "Using the variable on range scope .* in function literal",
    # gocritic chokes on if t.Before(today) {
    "ifElseChain:",
  ]

# vim: set ft=toml ts=4 sw=4 tw=0 et :
